// <auto-generated />
using System;
using ABAC.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ABAC.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191125202215_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ABAC.DAL.Entities.Attribute", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ResourceId");

                    b.Property<int?>("UserId");

                    b.Property<string>("Value");

                    b.HasKey("Name");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("Attribute");
                });

            modelBuilder.Entity("ABAC.DAL.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("resource");
                });

            modelBuilder.Entity("ABAC.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("ABAC.DAL.Entities.Attribute", b =>
                {
                    b.HasOne("ABAC.DAL.Entities.Resource")
                        .WithMany("Attributes")
                        .HasForeignKey("ResourceId");

                    b.HasOne("ABAC.DAL.Entities.User")
                        .WithMany("Attributes")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
